## Question 7

In [1]:
import pandas as pd
import numpy as np
import math
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

In [2]:
#Write to Csv File
intern=pd.read_excel('/Users/Asus/Documents/InternCsv/actual_july/Dispatch_July_2020.xlsx',header=None,index_col=None)

In [3]:
intern.head(5)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,Actual System Dispatch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-01 00:00:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Time,00:15:00,00:30:00,0:45,1:00,1:15,1:30,1:45,2:00,2:15,...,22:30,22:45,23:00,23:15,23:30,23:45,0:00,Energy/(MWh) *,NaN,NaN
2,Canyon,10,10,10,10,10,10,10,10,10,...,30,30,0,0,0,0,0,425,NaN,NaN
3,WPS,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,204,NaN,NaN
4,Olax,5,5,5,5,5,5,5,5,5,...,14,14,14,14,14,14,14,666,NaN,NaN

In [9]:
intern.to_csv('Dispatch.csv')

In [4]:
intern2=pd.read_excel('/Users/Asus/Documents/InternCsv/actual_july/Dispatch_July_2020.xlsx',index_col=None)

In [5]:
intern2.head(5)

,Actual System Dispatch,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,2020-07-01 00:00:00,Unnamed: 9,...,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99
0,Time,00:15:00,00:30:00,0:45,1:00,1:15,1:30,1:45,2:00,2:15,...,22:30,22:45,23:00,23:15,23:30,23:45,0:00,Energy/(MWh) *,NaN,NaN
1,Canyon,10,10,10,10,10,10,10,10,10,...,30,30,0,0,0,0,0,425,NaN,NaN
2,WPS,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,204,NaN,NaN
3,Olax,5,5,5,5,5,5,5,5,5,...,14,14,14,14,14,14,14,666,NaN,NaN
4,Nlax,46,45,19,20,19,15,9,10,10,...,29,27,44,39,37,37,17,1502,NaN,NaN

In [15]:
intern2.to_csv('Dispatch_header.csv')

## Question 8

In [6]:
# Complete information about data
intern2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 100 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Actual System Dispatch  47 non-null     object
 1   Unnamed: 1              48 non-null     object
 2   Unnamed: 2              48 non-null     object
 3   Unnamed: 3              48 non-null     object
 4   Unnamed: 4              48 non-null     object
 5   Unnamed: 5              48 non-null     object
 6   Unnamed: 6              48 non-null     object
 7   Unnamed: 7              48 non-null     object
 8   2020-07-01 00:00:00     48 non-null     object
 9   Unnamed: 9              48 non-null     object
 10  Unnamed: 10             48 non-null     object
 11  Unnamed: 11             48 non-null     object
 12  Unnamed: 12             48 non-null     object
 13  Unnamed: 13             48 non-null     object
 14  Unnamed: 14             48 non-null     object
 15  Unnamed: 15             48 non-null     object
 16  Unnamed: 16             48 non-null     object
 17  Unnamed: 17             48 non-null     object
 18  Unnamed: 18             48 non-null     object
 19  Unnamed: 19             48 non-null     object
 20  Unnamed: 20             48 non-null     object
 21  Unnamed: 21             48 non-null     object
 22  Unnamed: 22             48 non-null     object
 23  Unnamed: 23             48 non-null     object
 24  Unnamed: 24             48 non-null     object
 25  Unnamed: 25             48 non-null     object
 26  Unnamed: 26             48 non-null     object
 27  Unnamed: 27             48 non-null     object
 28  Unnamed: 28             48 non-null     object
 29  Unnamed: 29             48 non-null     object
 30  Unnamed: 30             48 non-null     object
 31  Unnamed: 31             48 non-null     object
 32  Unnamed: 32             48 non-null     object
 33  Unnamed: 33             48 non-null     object
 34  Unnamed: 34             48 non-null     object
 35  Unnamed: 35             48 non-null     object
 36  Unnamed: 36             48 non-null     object
 37  Unnamed: 37             48 non-null     object
 38  Unnamed: 38             48 non-null     object
 39  Unnamed: 39             48 non-null     object
 40  Unnamed: 40             48 non-null     object
 41  Unnamed: 41             48 non-null     object
 42  Unnamed: 42             48 non-null     object
 43  Unnamed: 43             48 non-null     object
 44  Unnamed: 44             48 non-null     object
 45  Unnamed: 45             48 non-null     object
 46  Unnamed: 46             48 non-null     object
 47  Unnamed: 47             48 non-null     object
 48  Unnamed: 48             48 non-null     object
 49  Unnamed: 49             48 non-null     object
 50  Unnamed: 50             48 non-null     object
 51  Unnamed: 51             48 non-null     object
 52  Unnamed: 52             48 non-null     object
 53  Unnamed: 53             48 non-null     object
 54  Unnamed: 54             48 non-null     object
 55  Unnamed: 55             48 non-null     object
 56  Unnamed: 56             48 non-null     object
 57  Unnamed: 57             48 non-null     object
 58  Unnamed: 58             48 non-null     object
 59  Unnamed: 59             48 non-null     object
 60  Unnamed: 60             48 non-null     object
 61  Unnamed: 61             48 non-null     object
 62  Unnamed: 62             48 non-null     object
 63  Unnamed: 63             48 non-null     object
 64  Unnamed: 64             48 non-null     object
 65  Unnamed: 65             48 non-null     object
 66  Unnamed: 66             48 non-null     object
 67  Unnamed: 67             48 non-null     object
 68  Unnamed: 68             48 non-null     object
 69  Unnamed: 69             48 non-null     object
 70  Unnamed: 70             48 non-null     object
 71  Unnamed: 71             48 non-null     object
 72  Unnamed: 72             48 non-null     object
 73  Unnamed: 73             48 non-null     object
 74  Unnamed: 74             48 non-null     object
 75  Unnamed: 75             48 non-null     object
 76  Unnamed: 76             48 non-null     object
 77  Unnamed: 77             48 non-null     object
 78  Unnamed: 78             48 non-null     object
 79  Unnamed: 79             48 non-null     object
 80  Unnamed: 80             48 non-null     object
 81  Unnamed: 81             48 non-null     object
 82  Unnamed: 82             48 non-null     object
 83  Unnamed: 83             48 non-null     object
 84  Unnamed: 84             48 non-null     object
 85  Unnamed: 85             48 non-null     object
 86  Unnamed: 86             48 non-null     object
 87  Unnamed: 87             48 non-null     object
 88  Unnamed: 88             48 non-null     object
 89  Unnamed: 89             48 non-null     object
 90  Unnamed: 90             48 non-null     object
 91  Unnamed: 91             48 non-null     object
 92  Unnamed: 92             48 non-null     object
 93  Unnamed: 93             48 non-null     object
 94  Unnamed: 94             48 non-null     object
 95  Unnamed: 95             48 non-null     object
 96  Unnamed: 96             48 non-null     object
 97  Unnamed: 97             48 non-null     object
 98  Unnamed: 98             7 non-null      object
 99  Unnamed: 99             8 non-null      object
dtypes: object(100)
memory usage: 37.6+ KB

In [7]:
# No Missing Values
intern2.isnull().head()

,Actual System Dispatch,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,2020-07-01 00:00:00,Unnamed: 9,...,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True

In [26]:
dict = {'Actual System Dispatch': 'Actual System Dispatch',
        '8': 'Actual System Dispatch',
        '18': 'Actual System Dispatch'}

# call rename () method
#intern.rename(columns=dict,
 #         inplace=True)

In [8]:
intern2.columns

Index(['Actual System Dispatch',             'Unnamed: 1',
                   'Unnamed: 2',             'Unnamed: 3',
                   'Unnamed: 4',             'Unnamed: 5',
                   'Unnamed: 6',             'Unnamed: 7',
            2020-07-01 00:00:00,             'Unnamed: 9',
                  'Unnamed: 10',            'Unnamed: 11',
                  'Unnamed: 12',            'Unnamed: 13',
                  'Unnamed: 14',            'Unnamed: 15',
                  'Unnamed: 16',            'Unnamed: 17',
                  'Unnamed: 18',            'Unnamed: 19',
                  'Unnamed: 20',            'Unnamed: 21',
                  'Unnamed: 22',            'Unnamed: 23',
                  'Unnamed: 24',            'Unnamed: 25',
                  'Unnamed: 26',            'Unnamed: 27',
                  'Unnamed: 28',            'Unnamed: 29',
                  'Unnamed: 30',            'Unnamed: 31',
                  'Unnamed: 32',            'Unnamed: 33',
                  'Unnamed: 34',            'Unnamed: 35',
                  'Unnamed: 36',            'Unnamed: 37',
                  'Unnamed: 38',            'Unnamed: 39',
                  'Unnamed: 40',            'Unnamed: 41',
                  'Unnamed: 42',            'Unnamed: 43',
                  'Unnamed: 44',            'Unnamed: 45',
                  'Unnamed: 46',            'Unnamed: 47',
                  'Unnamed: 48',            'Unnamed: 49',
                  'Unnamed: 50',            'Unnamed: 51',
                  'Unnamed: 52',            'Unnamed: 53',
                  'Unnamed: 54',            'Unnamed: 55',
                  'Unnamed: 56',            'Unnamed: 57',
                  'Unnamed: 58',            'Unnamed: 59',
                  'Unnamed: 60',            'Unnamed: 61',
                  'Unnamed: 62',            'Unnamed: 63',
                  'Unnamed: 64',            'Unnamed: 65',
                  'Unnamed: 66',            'Unnamed: 67',
                  'Unnamed: 68',            'Unnamed: 69',
                  'Unnamed: 70',            'Unnamed: 71',
                  'Unnamed: 72',            'Unnamed: 73',
                  'Unnamed: 74',            'Unnamed: 75',
                  'Unnamed: 76',            'Unnamed: 77',
                  'Unnamed: 78',            'Unnamed: 79',
                  'Unnamed: 80',            'Unnamed: 81',
                  'Unnamed: 82',            'Unnamed: 83',
                  'Unnamed: 84',            'Unnamed: 85',
                  'Unnamed: 86',            'Unnamed: 87',
                  'Unnamed: 88',            'Unnamed: 89',
                  'Unnamed: 90',            'Unnamed: 91',
                  'Unnamed: 92',            'Unnamed: 93',
                  'Unnamed: 94',            'Unnamed: 95',
                  'Unnamed: 96',            'Unnamed: 97',
                  'Unnamed: 98',            'Unnamed: 99'],
      dtype='object')

In [36]:
#headers = ["Actual","normalized-losses","make","fuel-type",
#           "aspiration", "num-of-doors","body-style"]

In [38]:
# Apply column names to headers
#intern.columns = headers
#intern.head()

## Question 9

In [10]:
inter=pd.read_csv('/Users/Asus/Documents/InternCsv/Dispatch_header.csv',index_col=None)

In [19]:
inter.head(5)

,Unnamed: 0,Actual System Dispatch,Courses_List,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,7/1/2020 0:00,...,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99
0,0,Time,0:15:00,0:30:00,0:45,1:00,1:15,1:30,1:45,2:00,...,22:30,22:45,23:00,23:15,23:30,23:45,0:00,Energy/(MWh) *,NaN,NaN
1,1,Canyon,10,10,10,10,10,10,10,10,...,30,30,0,0,0,0,0,425,NaN,NaN
2,2,WPS,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,204,NaN,NaN
3,3,Olax,5,5,5,5,5,5,5,5,...,14,14,14,14,14,14,14,666,NaN,NaN
4,4,Nlax,46,45,19,20,19,15,9,10,...,29,27,44,39,37,37,17,1502,NaN,NaN

In [22]:
# Replace (?) with (np.NaN)
inter.rename({'Unnamed: 1':'Courses_List','Unnamed: 2':'Initial Time'}, axis='columns', inplace=True)
inter.head()

,Unnamed: 0,Actual System Dispatch,Courses_List,Initial Time,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,7/1/2020 0:00,...,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99
0,0,Time,0:15:00,0:30:00,0:45,1:00,1:15,1:30,1:45,2:00,...,22:30,22:45,23:00,23:15,23:30,23:45,0:00,Energy/(MWh) *,NaN,NaN
1,1,Canyon,10,10,10,10,10,10,10,10,...,30,30,0,0,0,0,0,425,NaN,NaN
2,2,WPS,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,204,NaN,NaN
3,3,Olax,5,5,5,5,5,5,5,5,...,14,14,14,14,14,14,14,666,NaN,NaN
4,4,Nlax,46,45,19,20,19,15,9,10,...,29,27,44,39,37,37,17,1502,NaN,NaN

In [25]:
inter.columns = ['Time_'+str(col) for col in inter.columns]

In [26]:
inter.head()

,Time_TimeUnnamed: 0,Time_TimeActual System Dispatch,Time_TimeCourses_List,Time_TimeInitial Time,Time_TimeUnnamed: 3,Time_TimeUnnamed: 4,Time_TimeUnnamed: 5,Time_TimeUnnamed: 6,Time_TimeUnnamed: 7,Time_Time7/1/2020 0:00,...,Time_TimeUnnamed: 90,Time_TimeUnnamed: 91,Time_TimeUnnamed: 92,Time_TimeUnnamed: 93,Time_TimeUnnamed: 94,Time_TimeUnnamed: 95,Time_TimeUnnamed: 96,Time_TimeUnnamed: 97,Time_TimeUnnamed: 98,Time_TimeUnnamed: 99
0,0,Time,0:15:00,0:30:00,0:45,1:00,1:15,1:30,1:45,2:00,...,22:30,22:45,23:00,23:15,23:30,23:45,0:00,Energy/(MWh) *,NaN,NaN
1,1,Canyon,10,10,10,10,10,10,10,10,...,30,30,0,0,0,0,0,425,NaN,NaN
2,2,WPS,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,204,NaN,NaN
3,3,Olax,5,5,5,5,5,5,5,5,...,14,14,14,14,14,14,14,666,NaN,NaN
4,4,Nlax,46,45,19,20,19,15,9,10,...,29,27,44,39,37,37,17,1502,NaN,NaN

In [30]:
del inter["Time_TimeUnnamed: 99"]
inter.head()

,Time_TimeUnnamed: 0,Time_TimeActual System Dispatch,Time_TimeCourses_List,Time_TimeInitial Time,Time_TimeUnnamed: 3,Time_TimeUnnamed: 4,Time_TimeUnnamed: 5,Time_TimeUnnamed: 6,Time_TimeUnnamed: 7,Time_Time7/1/2020 0:00,...,Time_TimeUnnamed: 88,Time_TimeUnnamed: 89,Time_TimeUnnamed: 90,Time_TimeUnnamed: 91,Time_TimeUnnamed: 92,Time_TimeUnnamed: 93,Time_TimeUnnamed: 94,Time_TimeUnnamed: 95,Time_TimeUnnamed: 96,Time_TimeUnnamed: 97
0,0,Time,0:15:00,0:30:00,0:45,1:00,1:15,1:30,1:45,2:00,...,22:00,22:15,22:30,22:45,23:00,23:15,23:30,23:45,0:00,Energy/(MWh) *
1,1,Canyon,10,10,10,10,10,10,10,10,...,30,30,30,30,0,0,0,0,0,425
2,2,WPS,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,204
3,3,Olax,5,5,5,5,5,5,5,5,...,14,14,14,14,14,14,14,14,14,666
4,4,Nlax,46,45,19,20,19,15,9,10,...,16,29,29,27,44,39,37,37,17,1502

In [32]:
#inter.head()

In [43]:
#Converting Columns to relevant data typ6

#pd.to_datetime(intern['0'], format="%m/%d/%Y %H:%M:%S:%f")

inter.at[0,'Time_TimeUnnamed: 97']='1'
#inter["Time_TimeUnnamed: 97"] = pd.to_numeric(inter["Time_TimeUnnamed: 97"])
inter.head()

,Time_TimeUnnamed: 0,Time_TimeActual System Dispatch,Time_TimeCourses_List,Time_TimeInitial Time,Time_TimeUnnamed: 3,Time_TimeUnnamed: 4,Time_TimeUnnamed: 5,Time_TimeUnnamed: 6,Time_TimeUnnamed: 7,Time_Time7/1/2020 0:00,...,Time_TimeUnnamed: 88,Time_TimeUnnamed: 89,Time_TimeUnnamed: 90,Time_TimeUnnamed: 91,Time_TimeUnnamed: 92,Time_TimeUnnamed: 93,Time_TimeUnnamed: 94,Time_TimeUnnamed: 95,Time_TimeUnnamed: 96,Time_TimeUnnamed: 97
0,0,Time,0:15:00,0:30:00,0:45,1:00,1:15,1:30,1:45,2:00,...,22:00,22:15,22:30,22:45,23:00,23:15,23:30,23:45,0:00,1
1,1,Canyon,10,10,10,10,10,10,10,10,...,30,30,30,30,0,0,0,0,0,425
2,2,WPS,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,204
3,3,Olax,5,5,5,5,5,5,5,5,...,14,14,14,14,14,14,14,14,14,666
4,4,Nlax,46,45,19,20,19,15,9,10,...,16,29,29,27,44,39,37,37,17,1502

In [49]:
inter.loc[inter["Time_TimeUnnamed: 97"] == "Energy/(MWh) *", "Time_TimeUnnamed: 97"] = 1
#inter["Time_TimeUnnamed: 97"] = pd.to_numeric(inter["Time_TimeUnnamed: 97"])

In [52]:
#inter.head(50)
inter["Time_TimeUnnamed: 97"] = pd.to_numeric(inter["Time_TimeUnnamed: 97"])

In [53]:
#Column Time_TimeUnnamed: 97 is changed into Float Data type
inter.head(10)

,Time_TimeUnnamed: 0,Time_TimeActual System Dispatch,Time_TimeCourses_List,Time_TimeInitial Time,Time_TimeUnnamed: 3,Time_TimeUnnamed: 4,Time_TimeUnnamed: 5,Time_TimeUnnamed: 6,Time_TimeUnnamed: 7,Time_Time7/1/2020 0:00,...,Time_TimeUnnamed: 88,Time_TimeUnnamed: 89,Time_TimeUnnamed: 90,Time_TimeUnnamed: 91,Time_TimeUnnamed: 92,Time_TimeUnnamed: 93,Time_TimeUnnamed: 94,Time_TimeUnnamed: 95,Time_TimeUnnamed: 96,Time_TimeUnnamed: 97
0,0,Time,0:15:00,0:30:00,0:45,1:00,1:15,1:30,1:45,2:00,...,22:00,22:15,22:30,22:45,23:00,23:15,23:30,23:45,0:00,1.0
1,1,Canyon,10,10,10,10,10,10,10,10,...,30,30,30,30,0,0,0,0,0,425.0
2,2,WPS,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,204.0
3,3,Olax,5,5,5,5,5,5,5,5,...,14,14,14,14,14,14,14,14,14,666.0
4,4,Nlax,46,45,19,20,19,15,9,10,...,16,29,29,27,44,39,37,37,17,1502.0
5,5,Polp,21,19,20,19,18,17,22,20,...,22,22,23,21,25,23,20,20,20,1220.0
6,6,Upper Kothmale,0,0,0,0,0,0,0,0,...,40,0,0,0,0,0,0,0,0,336.0
7,7,Koth,54,42,43,44,39,41,40,37,...,36,45,47,37,61,50,41,39,33,1070.0
8,8,Vict,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,113.0
9,9,Rand,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,848.0

In [56]:
inter.to_csv('/Users/Asus/Documents/InternCsv/Dispatch_headerNew.csv')

## Question 10

In [57]:
### Loop the data lines
with open("/Users/Asus/Documents/InternCsv/Dispatch_headerNew.csv", 'r') as temp_f:
    # get No of columns in each line
    col_count = [ len(l.split(",")) for l in temp_f.readlines() ]

### Generate column names  (names will be 0, 1, 2, ..., maximum columns - 1)
column_names = [i for i in range(0, max(col_count))]

### Read csv
df = pd.read_csv("/Users/Asus/Documents/InternCsv/Dispatch_headerNew.csv", header=None, delimiter=",", names=column_names)
print(df)

      0                    1                                2   \
0    NaN  Time_TimeUnnamed: 0  Time_TimeActual System Dispatch
1    0.0                    0                             Time
2    1.0                    1                           Canyon
3    2.0                    2                              WPS
4    3.0                    3                             Olax
5    4.0                    4                             Nlax
6    5.0                    5                             Polp
7    6.0                    6                   Upper Kothmale
8    7.0                    7                             Koth
9    8.0                    8                             Vict
10   9.0                    9                             Rand
11  10.0                   10                             Rant
12  11.0                   11                              Uku
13  12.0                   12                             Bowa
14  13.0                   13                              Sam
15  14.0                   14                           Kukule
16  15.0                   15                           LVPS 1
17  16.0                   16                           LVPS 2
18  17.0                   17                           LVPS 3
19  18.0                   18                           Sapu A
20  19.0                   19                           Sapu B
21  20.0                   20                    Uthuru Janani
22  21.0                   21                            Barge
23  22.0                   22                             KCCP
24  23.0                   23                         ACE EMBP
25  24.0                   24                       ACE Matara
26  25.0                   25                       Asia Power
27  26.0                   26                              WCP
28  27.0                   27                       Sojitz CCP
29  28.0                   28                         KPS(GT7)
30  29.0                   29                          KPS(GT)
31  30.0                   30                    CEB Sup Power
32  31.0                   31                     VPOWER Hamb.
33  32.0                   32                    VPOWER Palle.
34  33.0                   33                    VPOWER Horona
35  34.0                   34                     ALTAQQA-Pol.
36  35.0                   35                    ALTAQQA-Mahi.
37  36.0                   36                          Solar**
38  37.0                   37                          Wind **
39  38.0                   38            CEB/IPP Mini Hydro***
40  39.0                   39                         Total MW
41  40.0                   40                             Time
42  41.0                   41                             Coal
43  42.0                   42                   Oil- CEB owned
44  43.0                   43                    Oil-IPP owned
45  44.0                   44                      Major Hydro
46  45.0                   45                             Wind
47  46.0                   46                            Solar
48  47.0                   47                              NaN

                       3                      4                    5   \
0   Time_TimeCourses_List  Time_TimeInitial Time  Time_TimeUnnamed: 3
1                 0:15:00                0:30:00                 0:45
2                      10                     10                   10
3                       0                      0                    0
4                       5                      5                    5
5                      46                     45                   19
6                      21                     19                   20
7                       0                      0                    0
8                      54                     42                   43
9                       0                      0                    0
10                      0                      0                    0
11                      0                      0                    0
12                     36                     36                   36
13                      0                      0                    0
14                      0                      0                    0
15                     53                     52                   52
16                    274                    274                  274
17                    270                    270                  269
18                    270                    270                  270
19                     33                     33                   33
20                     59                     59                   59
21                      0                      0                    0
22                     45                     45                   45
23                      0                      0                    0
24                      0                      0                    0
25                      0                      0                    0
26                      0                      0                    0
27                    140                    140                  140
28                      0                      0                    0
29                      0                      0                    0
30                      0                      0                    0
31                      0                      0                    0
32                      0                      0                    0
33                      0                      0                    0
34                      0                      0                    0
35                      0                      0                    0
36                      0                      0                    0
37                      0                      0                    0
38                     51                     49                   49
39                     65                     66                   66
40                   1434                   1417                 1393
41                   0:15                   0:30                 0:45
42                    814                    814                  813
43                    137                    137                  137
44                    140                    140                  140
45                    225                    209                  185
46                     51                     49                   49
47                      0                      0                    0
48                   1432                   1415                 1390

                     6                    7                    8   \
0   Time_TimeUnnamed: 4  Time_TimeUnnamed: 5  Time_TimeUnnamed: 6
1                  1:00                 1:15                 1:30
2                    10                   10                   10
3                     0                    0                    0
4                     5                    5                    5
5                    20                   19                   15
6                    19                   18                   17
7                     0                    0                    0
8                    44                   39                   41
9                     0                    0                    0
10                    0                    0                    0
11                    0                    0                    0
12                   36                   36                   21
13                    0                    0                    0
14                    0                    0                    0
15                   52                   52                   38
16                  274                  273                  274
17                  269                  269                  270
18                  270                  270                  271
19                   33                   39                   52
20                   60                   60                   59
21                    0                    0                    0
22                   45                   45                   45
23                    0                    0                    0
24                    0                    0                    0
25                    0                    0                    0
26                    0                    0                    0
27                  140                  140                  140
28                    0                    0                    0
29                    0                    0                    0
30                    0                    0                    0
31                    0                    0                    0
32                    0                    0                    0
33                    0                    0                    0
34                    0                    0                    0
35                    0                    0                    0
36                    0                    0                    0
37                    0                    0                    0
38                   48                   46                   48
39                   65                   64                   64
40                 1392                 1387                 1371
41                 1:00                 1:15                 1:30
42                  813                  812                  815
43                  138                  144                  156
44                  140                  140                  140
45                  186                  179                  147
46                   48                   46                   48
47                    0                    0                    0
48                 1390                 1385                 1370

                     9   ...                    90                    91  \
0   Time_TimeUnnamed: 7  ...  Time_TimeUnnamed: 88  Time_TimeUnnamed: 89
1                  1:45  ...                 22:00                 22:15
2                    10  ...                    30                    30
3                     0  ...                     0                     0
4                     5  ...                    14                    14
5                     9  ...                    16                    29
6                    22  ...                    22                    22
7                     0  ...                    40                     0
8                    40  ...                    36                    45
9                     0  ...                     0                     0
10                    0  ...                     0                     0
11                    0  ...                    19                     0
12                    0  ...                    36                    36
13                    0  ...                    39                    39
14                    0  ...                     0                     0
15                   26  ...                    26                    26
16                  271  ...                   272                   271
17                  270  ...                   269                   269
18                  270  ...                   270                   270
19                   54  ...                    54                    54
20                   61  ...                    60                    61
21                    0  ...                    20                    20
22                   45  ...                    60                    60
23                    0  ...                     0                     0
24                    0  ...                    92                    92
25                    0  ...                    24                    24
26                    0  ...                    44                    38
27                  139  ...                   139                   139
28                    0  ...                   138                   118
29                    0  ...                     0                     0
30                    0  ...                     0                     0
31                    0  ...                     0                     0
32                    0  ...                     0                     0
33                    0  ...                     0                     0
34                    0  ...                     0                     0
35                    0  ...                     0                     0
36                    0  ...                     0                     0
37                    0  ...                     0                     0
38                   52  ...                    58                    56
39                   68  ...                   120                   120
40                 1342  ...                  1900                  1835
41                 1:45  ...                 22:00                 22:15
42                  811  ...                   811                   810
43                  160  ...                   194                   195
44                  139  ...                   437                   411
45                  112  ...                   278                   241
46                   52  ...                    58                    56
47                    0  ...                     0                     0
48                 1342  ...                  1898                  1833

                      92                    93                    94  \
0   Time_TimeUnnamed: 90  Time_TimeUnnamed: 91  Time_TimeUnnamed: 92
1                  22:30                 22:45                 23:00
2                     30                    30                     0
3                      0                     0                     0
4                     14                    14                    14
5                     29                    27                    44
6                     23                    21                    25
7                      0                     0                     0
8                     47                    37                    61
9                      0                     0                     0
10                     0                     0                     0
11                     0                     0                     0
12                    36                    36                    36
13                    39                    39                    39
14                     0                     0                     0
15                     0                     0                     0
16                   272                   272                   273
17                   269                   269                   269
18                   270                   269                   271
19                    54                    54                    53
20                    61                    61                    62
21                    20                    20                    20
22                    60                    60                    60
23                     0                     0                     0
24                    92                    92                    92
25                    24                    24                    24
26                    27                    21                    21
27                   139                   139                   139
28                    98                    84                    17
29                     0                     0                     0
30                     0                     0                     0
31                     0                     0                     0
32                     0                     0                     0
33                     0                     0                     0
34                     0                     0                     0
35                     0                     0                     0
36                     0                     0                     0
37                     0                     0                     0
38                    55                    57                    56
39                    58                    59                    60
40                  1719                  1685                  1637
41                 22:30                 22:45                 23:00
42                   811                   810                   813
43                   195                   195                   195
44                   380                   360                   293
45                   218                   204                   219
46                    55                    57                    56
47                     0                     0                     0
48                  1717                  1685                  1636

                      95                    96                    97  \
0   Time_TimeUnnamed: 93  Time_TimeUnnamed: 94  Time_TimeUnnamed: 95
1                  23:15                 23:30                 23:45
2                      0                     0                     0
3                      0                     0                     0
4                     14                    14                    14
5                     39                    37                    37
6                     23                    20                    20
7                      0                     0                     0
8                     50                    41                    39
9                      0                     0                     0
10                     0                     0                     0
11                     0                     0                     0
12                    36                    36                    36
13                    39                    20                     0
14                     0                     0                     0
15                     0                     0                     0
16                   272                   271                   271
17                   269                   270                   269
18                   271                   270                   268
19                    53                    54                    54
20                    61                    61                    61
21                    20                    20                    20
22                    60                    60                    60
23                     0                     0                     0
24                    92                    92                    92
25                    24                    24                     0
26                    16                     9                     0
27                   139                   139                   140
28                     0                     0                     0
29                     0                     0                     0
30                     0                     0                     0
31                     0                     0                     0
32                     0                     0                     0
33                     0                     0                     0
34                     0                     0                     0
35                     0                     0                     0
36                     0                     0                     0
37                     0                     0                     0
38                    58                    56                    60
39                    62                    63                    64
40                  1599                  1558                  1505

## Question 11

In [73]:
#Get the columns in different files with different format into same format
july1=pd.read_excel('/Users/Asus/Documents/InternCsv/forcast_july/july3.xls',index_col=None)
july2=pd.read_excel('/Users/Asus/Documents/InternCsv/forcast_july/july4.xls',index_col=None)

In [74]:
july1.head(4)

,3. Day Ahead Economic Dispatch for next day in MW,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,Unnamed: 144,Unnamed: 145,Unnamed: 146,Unnamed: 147
0,Date,2020-07-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,00:00:00,00:30:00,01:00:00,01:30:00,02:00:00,02:30:00,03:00:00,03:30:00,04:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,WPS,23.388,10,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Victoria
3,Cany,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kothmale

In [75]:
july2.drop(july1.iloc[:, 50:147], inplace = True, axis = 1)

In [76]:
july1.drop(july1.iloc[:, 50:147], inplace = True, axis = 1)

In [77]:
july1.head(5)

,3. Day Ahead Economic Dispatch for next day in MW,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 147
0,Date,2020-07-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2020-07-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,00:00:00,00:30:00,01:00:00,01:30:00,02:00:00,02:30:00,03:00:00,03:30:00,04:00:00,...,20:00:00,20:30:00,21:00:00,21:30:00,22:00:00,22:30:00,23:00:00,23:30:00,Energy,NaN
2,WPS,23.388,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,286.979,Victoria
3,Cany,0,0,0,0,0,0,0,0,0,...,30,20.056,20.056,11.04,0,0,0,0,412.806,Kothmale
4,Olax,10,10,10,10,10,10,10,10,10,...,0,0,0,0,0,0,0,0,600,Samanalawewa

In [78]:
july2.head(5)

,3. Day Ahead Economic Dispatch for next day in MW,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 147
0,Date,2020-07-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2020-07-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,00:00:00,00:30:00,01:00:00,01:30:00,02:00:00,02:30:00,03:00:00,03:30:00,04:00:00,...,20:00:00,20:30:00,21:00:00,21:30:00,22:00:00,22:30:00,23:00:00,23:30:00,Energy,NaN
2,WPS,22.96,22.96,0,0,0,0,0,0,0,...,10,10,0,0,0,0,0,0,286.979,Victoria
3,Cany,11.04,11.04,0,0,0,0,0,0,0,...,30,30,30,29.917,13.387,13.387,0,0,451.198,Kothmale
4,Olax,10,10,10,10,10,10,10,10,10,...,54,54,54,54,10,10,10,0,599.998,Samanalawewa

In [105]:
july1.loc[july1["Unnamed: 147"] == "NaN", "Unnamed: 147"] = 0
july1.head(60)

,3. Day Ahead Economic Dispatch for next day in MW,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 147
0,Date,2020-07-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2020-07-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,00:00:00,00:30:00,01:00:00,01:30:00,02:00:00,02:30:00,03:00:00,03:30:00,04:00:00,...,20:00:00,20:30:00,21:00:00,21:30:00,22:00:00,22:30:00,23:00:00,23:30:00,Energy,NaN
2,WPS,23.388,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,286.979,Victoria
3,Cany,0,0,0,0,0,0,0,0,0,...,30,20.056,20.056,11.04,0,0,0,0,412.806,Kothmale
4,Olax,10,10,10,10,10,10,10,10,10,...,0,0,0,0,0,0,0,0,600,Samanalawewa
5,Nlax,19.92,19.92,19.92,19.92,19.92,19.92,19.92,19.92,19.92,...,99.602,65.838,65.838,19.92,19.92,19.92,0,0,1400.001,Laxapana
6,Polp,21.722,6.1039,6.1039,6.1039,6.1039,6.1039,6.1039,6.1039,6.1039,...,74.361,64.069,64.069,64.069,47.399,47.399,6.1039,6.1039,1160.69495,Up Koth
7,UKPS,0,0,0,0,0,0,0,0,0,...,109.11,109.11,109.11,109.11,43.394,83.844,83.844,43.394,509.123,KCCP GT
8,Koth,40,40,40,40,40,40,40,40,40,...,71.37,71.37,71.37,40,40,40,40,40,1099.9975,KCCP
9,Victoria,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,200.0015,NaN
10,Rand,0,0,0,0,0,0,0,0,0,...,43,0,0,0,0,0,0,0,563.357,NaN
11,Rant,0,0,0,0,0,0,0,0,0,...,20,20,20,20,0,0,0,0,380,NaN
12,Uku,40,40,40,40,40,40,40,40,40,...,40,40,40,40,40,40,40,40,960,NaN
13,Bowa,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,180.0,NaN
14,Sama,0,0,0,0,0,0,0,0,0,...,99.999,99.999,10.21,10.21,0,0,0,0,699.9975,NaN
15,Kukule,0,0,0,0,0,0,0,0,0,...,63.842,63.842,54.631,33.935,28.567,60.817,31.032,31.032,765.363,NaN
16,PCCP I,270,270,270,270,270,270,270,270,270,...,270,270,270,270,270,270,270,270,6480,NaN
17,PCCP II,270,270,270,270,270,270,270,270,270,...,270,270,270,270,270,270,270,270,6480,NaN
18,PCCP III,229,259,270,270,270,270,270,270,270,...,270,270,270,270,270,270,270,270,6454,NaN
19,KPS,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
20,CEB_EMERGENCY,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
21,GT 07,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
22,SPS A,54,54,54,33,33,33,33,33,33,...,54,54,54,54,54,54,54,54,1233,NaN
23,SPS B,63,63,63,63,49,49,49,49,63,...,63,63,63,63,63,63,63,63,1484,NaN
24,Asia Power,0,0,0,0,0,0,0,0,0,...,32.9,32.9,32.9,32.9,32.9,34.2,34.2,32.9,630.05025,NaN
25,Barge,60,60,60,35.516,34,34,34,34,35.516,...,60,60,60,60,60,60,60,60,1363.516,NaN
26,ACE (Matara),0,0,0,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,304,NaN
27,Ace (Embilipitiya),66.97,31.46,31.46,31.46,31.46,31.46,31.46,31.46,31.46,...,92.82,92.82,92.82,92.82,92.82,92.82,92.82,37.18,1906.4628,NaN
28,NORTHERN_Power,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
29,Uthuru_Janani,20,15.516,13.516,4,0,0,0,0,0,...,20,20,20,20,20,20,20,19.39,336.1319,NaN
30,KCCP GT(N),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
31,KCCP ST(N),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
32,KCCP GT(D),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
33,KCCP ST(D),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
34,Sojitz CCP,0,0,0,0,0,0,0,0,0,...,163,163,163,163,163,0,0,0,2150,NaN
35,WCP_GT1,85,85,85,85,84.072,78.447,67.197,75.947,85,...,85,85,85,85,85,85,85,85,2022.8315,NaN
36,WCP_GT2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
37,WCP_ST,50,50,50,50,49.443,46.068,39.318,44.568,50,...,50,50,50,50,50,50,50,50,1189.6985,NaN
38,VPOWER_Palle,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
39,ALTAAQ_Mahiya,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
40,ALTAAQ_Polon,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
41,VPOWER_Hamb,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
42,VPOWER_Horana,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
43,Wind,51,49,46,52,53,53,54,54,58,...,62,62,54,56,56,57,58,60,1283,NaN
44,Solar,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,136.5,NaN
45,Mini Hydro***,60,60,58,62,62,64,67,69,63,...,113,113,113,113,113,51,55,57,NaN,NaN
46,Total Generation,1434,1392.9999,1386.9999,1341.9999,1321.9989,1314.9989,1300.9989,1316.9989,1344.9999,...,2273.004,2176.004,2069.004,1964.004,1835,1685,1598.9999,1504.9999,42671.5114,NaN
47,Total Hydro,155.03,126.0239,116.0239,116.0239,116.0239,116.0239,116.0239,116.0239,116.0239,...,651.284,554.284,455.284,348.284,219.28,291.98,200.9799,160.5299,9218.32045,NaN
48,Total Thermal,1167.97,1157.976,1166.976,1111.976,1090.975,1081.975,1063.975,1077.975,1107.976,...,1446.72,1446.72,1446.72,1446.72,1446.72,1285.02,1285.02,1227.47,32033.69095,NaN
49,Total NCRE ***,111,109,104,114,115,117,121,123,121,...,175,175,167,169,169,108,113,117,NaN,NaN
50,Generation Summery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,2020-07-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Total Energy / (GWh),44.060511,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,Hydro Energy / (GWh),9.21832,0.20922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Thermal Energy /(GWh),32.033691,0.727039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NCRE Energy / (GWh),2.8085,0.063742,NaN,NaN,,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,Note ***,Please note that NCRE forecasting based only o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,Remarks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
july1.columns

Index(['3.    Day Ahead Economic Dispatch for next day in MW', 'Unnamed: 1',
       'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47',
       'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 147'],
      dtype='object')

In [109]:
july1.fillna(0,inplace=True)
july1.head(60)

,3. Day Ahead Economic Dispatch for next day in MW,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 147
0,Date,2020-07-03 00:00:00,0,0,0,0,0,0,0,0,...,2020-07-03 00:00:00,0,0,0,0,0,0,0,0,0
1,0,00:00:00,00:30:00,01:00:00,01:30:00,02:00:00,02:30:00,03:00:00,03:30:00,04:00:00,...,20:00:00,20:30:00,21:00:00,21:30:00,22:00:00,22:30:00,23:00:00,23:30:00,Energy,0
2,WPS,23.388,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,286.979,Victoria
3,Cany,0,0,0,0,0,0,0,0,0,...,30,20.056,20.056,11.04,0,0,0,0,412.806,Kothmale
4,Olax,10,10,10,10,10,10,10,10,10,...,0,0,0,0,0,0,0,0,600,Samanalawewa
5,Nlax,19.92,19.92,19.92,19.92,19.92,19.92,19.92,19.92,19.92,...,99.602,65.838,65.838,19.92,19.92,19.92,0,0,1400.001,Laxapana
6,Polp,21.722,6.1039,6.1039,6.1039,6.1039,6.1039,6.1039,6.1039,6.1039,...,74.361,64.069,64.069,64.069,47.399,47.399,6.1039,6.1039,1160.69495,Up Koth
7,UKPS,0,0,0,0,0,0,0,0,0,...,109.11,109.11,109.11,109.11,43.394,83.844,83.844,43.394,509.123,KCCP GT
8,Koth,40,40,40,40,40,40,40,40,40,...,71.37,71.37,71.37,40,40,40,40,40,1099.9975,KCCP
9,Victoria,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,200.0015,0
10,Rand,0,0,0,0,0,0,0,0,0,...,43,0,0,0,0,0,0,0,563.357,0
11,Rant,0,0,0,0,0,0,0,0,0,...,20,20,20,20,0,0,0,0,380,0
12,Uku,40,40,40,40,40,40,40,40,40,...,40,40,40,40,40,40,40,40,960,0
13,Bowa,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,180.0,0
14,Sama,0,0,0,0,0,0,0,0,0,...,99.999,99.999,10.21,10.21,0,0,0,0,699.9975,0
15,Kukule,0,0,0,0,0,0,0,0,0,...,63.842,63.842,54.631,33.935,28.567,60.817,31.032,31.032,765.363,0
16,PCCP I,270,270,270,270,270,270,270,270,270,...,270,270,270,270,270,270,270,270,6480,0
17,PCCP II,270,270,270,270,270,270,270,270,270,...,270,270,270,270,270,270,270,270,6480,0
18,PCCP III,229,259,270,270,270,270,270,270,270,...,270,270,270,270,270,270,270,270,6454,0
19,KPS,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,CEB_EMERGENCY,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,GT 07,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,SPS A,54,54,54,33,33,33,33,33,33,...,54,54,54,54,54,54,54,54,1233,0
23,SPS B,63,63,63,63,49,49,49,49,63,...,63,63,63,63,63,63,63,63,1484,0
24,Asia Power,0,0,0,0,0,0,0,0,0,...,32.9,32.9,32.9,32.9,32.9,34.2,34.2,32.9,630.05025,0
25,Barge,60,60,60,35.516,34,34,34,34,35.516,...,60,60,60,60,60,60,60,60,1363.516,0
26,ACE (Matara),0,0,0,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,304,0
27,Ace (Embilipitiya),66.97,31.46,31.46,31.46,31.46,31.46,31.46,31.46,31.46,...,92.82,92.82,92.82,92.82,92.82,92.82,92.82,37.18,1906.4628,0
28,NORTHERN_Power,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,Uthuru_Janani,20,15.516,13.516,4,0,0,0,0,0,...,20,20,20,20,20,20,20,19.39,336.1319,0
30,KCCP GT(N),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,KCCP ST(N),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,KCCP GT(D),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,KCCP ST(D),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,Sojitz CCP,0,0,0,0,0,0,0,0,0,...,163,163,163,163,163,0,0,0,2150,0
35,WCP_GT1,85,85,85,85,84.072,78.447,67.197,75.947,85,...,85,85,85,85,85,85,85,85,2022.8315,0
36,WCP_GT2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,WCP_ST,50,50,50,50,49.443,46.068,39.318,44.568,50,...,50,50,50,50,50,50,50,50,1189.6985,0
38,VPOWER_Palle,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,ALTAAQ_Mahiya,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,ALTAAQ_Polon,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,VPOWER_Hamb,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,VPOWER_Horana,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,Wind,51,49,46,52,53,53,54,54,58,...,62,62,54,56,56,57,58,60,1283,0
44,Solar,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,136.5,0
45,Mini Hydro***,60,60,58,62,62,64,67,69,63,...,113,113,113,113,113,51,55,57,0,0
46,Total Generation,1434,1392.9999,1386.9999,1341.9999,1321.9989,1314.9989,1300.9989,1316.9989,1344.9999,...,2273.004,2176.004,2069.004,1964.004,1835,1685,1598.9999,1504.9999,42671.5114,0
47,Total Hydro,155.03,126.0239,116.0239,116.0239,116.0239,116.0239,116.0239,116.0239,116.0239,...,651.284,554.284,455.284,348.284,219.28,291.98,200.9799,160.5299,9218.32045,0
48,Total Thermal,1167.97,1157.976,1166.976,1111.976,1090.975,1081.975,1063.975,1077.975,1107.976,...,1446.72,1446.72,1446.72,1446.72,1446.72,1285.02,1285.02,1227.47,32033.69095,0
49,Total NCRE ***,111,109,104,114,115,117,121,123,121,...,175,175,167,169,169,108,113,117,0,0
50,Generation Summery,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,0,2020-07-03 00:00:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
52,Total Energy / (GWh),44.060511,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
53,Hydro Energy / (GWh),9.21832,0.20922,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
54,Thermal Energy /(GWh),32.033691,0.727039,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55,NCRE Energy / (GWh),2.8085,0.063742,0,0,,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57,Note ***,Please note that NCRE forecasting based only o...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
58,Remarks,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [117]:
#inter.head(50)
#july1.dtypes
july1.convert_dtypes()
july1.head(40)

,3. Day Ahead Economic Dispatch for next day in MW,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 147
0,Date,2020-07-03 00:00:00,0,0,0,0,0,0,0,0,...,2020-07-03 00:00:00,0,0,0,0,0,0,0,0,0
1,0,00:00:00,00:30:00,01:00:00,01:30:00,02:00:00,02:30:00,03:00:00,03:30:00,04:00:00,...,20:00:00,20:30:00,21:00:00,21:30:00,22:00:00,22:30:00,23:00:00,23:30:00,Energy,0
2,WPS,23.388,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,286.979,Victoria
3,Cany,0,0,0,0,0,0,0,0,0,...,30,20.056,20.056,11.04,0,0,0,0,412.806,Kothmale
4,Olax,10,10,10,10,10,10,10,10,10,...,0,0,0,0,0,0,0,0,600,Samanalawewa
5,Nlax,19.92,19.92,19.92,19.92,19.92,19.92,19.92,19.92,19.92,...,99.602,65.838,65.838,19.92,19.92,19.92,0,0,1400.001,Laxapana
6,Polp,21.722,6.1039,6.1039,6.1039,6.1039,6.1039,6.1039,6.1039,6.1039,...,74.361,64.069,64.069,64.069,47.399,47.399,6.1039,6.1039,1160.69495,Up Koth
7,UKPS,0,0,0,0,0,0,0,0,0,...,109.11,109.11,109.11,109.11,43.394,83.844,83.844,43.394,509.123,KCCP GT
8,Koth,40,40,40,40,40,40,40,40,40,...,71.37,71.37,71.37,40,40,40,40,40,1099.9975,KCCP
9,Victoria,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,200.0015,0
10,Rand,0,0,0,0,0,0,0,0,0,...,43,0,0,0,0,0,0,0,563.357,0
11,Rant,0,0,0,0,0,0,0,0,0,...,20,20,20,20,0,0,0,0,380,0
12,Uku,40,40,40,40,40,40,40,40,40,...,40,40,40,40,40,40,40,40,960,0
13,Bowa,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,180.0,0
14,Sama,0,0,0,0,0,0,0,0,0,...,99.999,99.999,10.21,10.21,0,0,0,0,699.9975,0
15,Kukule,0,0,0,0,0,0,0,0,0,...,63.842,63.842,54.631,33.935,28.567,60.817,31.032,31.032,765.363,0
16,PCCP I,270,270,270,270,270,270,270,270,270,...,270,270,270,270,270,270,270,270,6480,0
17,PCCP II,270,270,270,270,270,270,270,270,270,...,270,270,270,270,270,270,270,270,6480,0
18,PCCP III,229,259,270,270,270,270,270,270,270,...,270,270,270,270,270,270,270,270,6454,0
19,KPS,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,CEB_EMERGENCY,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,GT 07,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,SPS A,54,54,54,33,33,33,33,33,33,...,54,54,54,54,54,54,54,54,1233,0
23,SPS B,63,63,63,63,49,49,49,49,63,...,63,63,63,63,63,63,63,63,1484,0
24,Asia Power,0,0,0,0,0,0,0,0,0,...,32.9,32.9,32.9,32.9,32.9,34.2,34.2,32.9,630.05025,0
25,Barge,60,60,60,35.516,34,34,34,34,35.516,...,60,60,60,60,60,60,60,60,1363.516,0
26,ACE (Matara),0,0,0,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,304,0
27,Ace (Embilipitiya),66.97,31.46,31.46,31.46,31.46,31.46,31.46,31.46,31.46,...,92.82,92.82,92.82,92.82,92.82,92.82,92.82,37.18,1906.4628,0
28,NORTHERN_Power,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,Uthuru_Janani,20,15.516,13.516,4,0,0,0,0,0,...,20,20,20,20,20,20,20,19.39,336.1319,0
30,KCCP GT(N),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,KCCP ST(N),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,KCCP GT(D),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,KCCP ST(D),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,Sojitz CCP,0,0,0,0,0,0,0,0,0,...,163,163,163,163,163,0,0,0,2150,0
35,WCP_GT1,85,85,85,85,84.072,78.447,67.197,75.947,85,...,85,85,85,85,85,85,85,85,2022.8315,0
36,WCP_GT2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,WCP_ST,50,50,50,50,49.443,46.068,39.318,44.568,50,...,50,50,50,50,50,50,50,50,1189.6985,0
38,VPOWER_Palle,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,ALTAAQ_Mahiya,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [118]:
july1.dtypes

3.    Day Ahead Economic Dispatch for next day in MW    object
Unnamed: 1                                              object
Unnamed: 2                                              object
Unnamed: 3                                              object
Unnamed: 4                                              object
Unnamed: 5                                              object
Unnamed: 6                                              object
Unnamed: 7                                              object
Unnamed: 8                                              object
Unnamed: 9                                              object
Unnamed: 10                                             object
Unnamed: 11                                             object
Unnamed: 12                                             object
Unnamed: 13                                             object
Unnamed: 14                                             object
Unnamed: 15                                             object
Unnamed: 16                                             object
Unnamed: 17                                             object
Unnamed: 18                                             object
Unnamed: 19                                             object
Unnamed: 20                                             object
Unnamed: 21                                             object
Unnamed: 22                                             object
Unnamed: 23                                             object
Unnamed: 24                                             object
Unnamed: 25                                             object
Unnamed: 26                                             object
Unnamed: 27                                             object
Unnamed: 28                                             object
Unnamed: 29                                             object
Unnamed: 30                                             object
Unnamed: 31                                             object
Unnamed: 32                                             object
Unnamed: 33                                             object
Unnamed: 34                                             object
Unnamed: 35                                             object
Unnamed: 36                                             object
Unnamed: 37                                             object
Unnamed: 38                                             object
Unnamed: 39                                             object
Unnamed: 40                                             object
Unnamed: 41                                             object
Unnamed: 42                                             object
Unnamed: 43                                             object
Unnamed: 44                                             object
Unnamed: 45                                             object
Unnamed: 46                                             object
Unnamed: 47                                             object
Unnamed: 48                                             object
Unnamed: 49                                             object
Unnamed: 147                                            object
dtype: object

In [119]:
july2.fillna(0,inplace=True)
july2.head(30)

,3. Day Ahead Economic Dispatch for next day in MW,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 147
0,Date,2020-07-04 00:00:00,0,0,0,0,0,0,0,0,...,2020-07-04 00:00:00,0,0,0,0,0,0,0,0,0
1,0,00:00:00,00:30:00,01:00:00,01:30:00,02:00:00,02:30:00,03:00:00,03:30:00,04:00:00,...,20:00:00,20:30:00,21:00:00,21:30:00,22:00:00,22:30:00,23:00:00,23:30:00,Energy,0
2,WPS,22.96,22.96,0,0,0,0,0,0,0,...,10,10,0,0,0,0,0,0,286.979,Victoria
3,Cany,11.04,11.04,0,0,0,0,0,0,0,...,30,30,30,29.917,13.387,13.387,0,0,451.198,Kothmale
4,Olax,10,10,10,10,10,10,10,10,10,...,54,54,54,54,10,10,10,0,599.998,Samanalawewa
5,Nlax,22.388,22.388,22.388,19.92,19.92,19.92,19.92,19.92,19.92,...,92.43,92.43,92.43,53.91,53.91,19.92,19.92,0,1500.003,Laxapana
6,Polp,18.613,17.613,17.613,6.1039,6.1039,6.1039,6.1039,6.1039,6.1039,...,78.479,78.479,52.982,52.982,52.982,52.982,50.476,30.396,1211.5409,Up Koth
7,UKPS,0,0,0,0,0,0,0,0,0,...,150,68,68,68,43.394,43.394,43.394,43.394,932.467,KCCP GT
8,Koth,40,40,40,40,40,58.9,58.45,58.05,58.25,...,62.01,62.01,62.01,62.01,62.01,40,40,40,1199.999,KCCP
9,Victoria,0,0,0,0,0,0,0,0,0,...,44.211,44.211,20.716,0,0,0,0,0,200.0025,0
10,Rand,0,0,0,0,0,0,0,0,0,...,43,43,0,0,0,0,0,0,563.357,0
11,Rant,0,0,0,0,0,0,0,0,0,...,20,20,20,20,0,0,0,0,380,0
12,Uku,40,40,40,40,40,40,40,40,40,...,40,40,40,40,40,40,40,40,600,0
13,Bowa,0,0,0,0,0,0,0,0,0,...,35.864,35.864,35.864,35.864,11,0,0,0,399.9995,0
14,Sama,0,0,0,0,0,0,0,0,0,...,99.999,99.999,99.999,66.317,66.317,66.317,10.21,10.21,649.996,0
15,Kukule,74.999,74.999,74.999,74.999,74.999,74.999,74.999,74.999,74.999,...,74.999,74.999,74.999,74.999,74.999,74.999,74.999,74.999,1799.976,0
16,PCCP I,270,270,270,270,270,264.58,261.03,257.43,267.23,...,270,270,270,270,270,270,270,270,5810.135,0
17,PCCP II,270,270,270,270,270,270,270,270,270,...,270,270,270,270,270,270,270,270,5825,0
18,PCCP III,270,270,270,270,270,270,270,270,270,...,270,270,270,270,270,270,270,270,5825,0
19,KPS,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,CEB_EMERGENCY,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,GT 07,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,SPS A,18,0,0,0,0,0,0,0,0,...,54,54,54,54,54,54,54,54,1026,0
23,SPS B,54,27,27,27,18,14,14,14,14,...,63,63,63,63,63,63,63,63,1279,0
24,Asia Power,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,Barge,60,60,60,55.977,39.977,25.5,25.5,25.5,25.5,...,60,60,60,60,60,60,60,60,1351.477,0
26,ACE (Matara),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,Ace (Embilipitiya),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,NORTHERN_Power,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,Uthuru_Janani,0,0,0,0,0,0,0,0,0,...,10.007,10.007,4,4,4,4,4,4,151.367,0

In [120]:
july1.convert_dtypes()
july1.dtypes

3.    Day Ahead Economic Dispatch for next day in MW    object
Unnamed: 1                                              object
Unnamed: 2                                              object
Unnamed: 3                                              object
Unnamed: 4                                              object
Unnamed: 5                                              object
Unnamed: 6                                              object
Unnamed: 7                                              object
Unnamed: 8                                              object
Unnamed: 9                                              object
Unnamed: 10                                             object
Unnamed: 11                                             object
Unnamed: 12                                             object
Unnamed: 13                                             object
Unnamed: 14                                             object
Unnamed: 15                                             object
Unnamed: 16                                             object
Unnamed: 17                                             object
Unnamed: 18                                             object
Unnamed: 19                                             object
Unnamed: 20                                             object
Unnamed: 21                                             object
Unnamed: 22                                             object
Unnamed: 23                                             object
Unnamed: 24                                             object
Unnamed: 25                                             object
Unnamed: 26                                             object
Unnamed: 27                                             object
Unnamed: 28                                             object
Unnamed: 29                                             object
Unnamed: 30                                             object
Unnamed: 31                                             object
Unnamed: 32                                             object
Unnamed: 33                                             object
Unnamed: 34                                             object
Unnamed: 35                                             object
Unnamed: 36                                             object
Unnamed: 37                                             object
Unnamed: 38                                             object
Unnamed: 39                                             object
Unnamed: 40                                             object
Unnamed: 41                                             object
Unnamed: 42                                             object
Unnamed: 43                                             object
Unnamed: 44                                             object
Unnamed: 45                                             object
Unnamed: 46                                             object
Unnamed: 47                                             object
Unnamed: 48                                             object
Unnamed: 49                                             object
Unnamed: 147                                            object
dtype: object